#!/bin/sh

DIS1=$1
DIS2=$2


choices="primary\ndual\nsecondary\nManual selection"

chosen=$(echo -e "$choices" | $3 -i)

case "$chosen" in
	dual) xrandr --output $DIS1 --auto --output $DIS2 --auto --right-of $DIS1 ;;
	primary) xrandr --output $DIS1 --auto --output $DIS2 --off ;;
	secondary) xrandr --output $DIS2 --auto --output $DIS1 --off ;;
	"Manual selection") arandr ;;
esac
